server:
  port: 8084

spring:
  application:
    name: zuul-service

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8671/eureka
#    instance: localhost

zuul:
  prefix: /api
  routes:
    movie-catalog-service:
      path: /moviecatalogservice/**
      service-id: movie-catalog-service
    movie-info-service:
      path: /movieinfoservice/**
      service-id: movie-info-service
    ratings-data-service:
      path: /ratingsdataservice/**
      service-id: ratings-data-service

